CC = gcc

COMMON_CFLAGS = -Wall -std=c99 -I"SDL2/include" -Dmain=SDL_main
DEBUG_CFLAGS = -g
RELEASE_CFLAGS = -O2 -DNDEBUG

LDFLAGS = -L"SDL2/lib" -lSDL2 -lSDL2main

DEBUG_TARGET = fc.exe
RELEASE_TARGET = fc-release.exe

SRCDIR = ./
DEST_DIR = build
DEBUG_OBJDIR = $(DEST_DIR)/debug
RELEASE_OBJDIR = $(DEST_DIR)/release

SRCS = $(wildcard $(SRCDIR)/*.c)
SRC_NAMES = $(notdir $(SRCS:.c=.o))

DEBUG_OBJS = $(addprefix $(DEBUG_OBJDIR)/, $(SRC_NAMES))
RELEASE_OBJS = $(addprefix $(RELEASE_OBJDIR)/, $(SRC_NAMES))

DEBUG_TARGET_PATH = $(DEST_DIR)/$(DEBUG_TARGET)
RELEASE_TARGET_PATH = $(DEST_DIR)/$(RELEASE_TARGET)

all: debug

debug: $(DEBUG_TARGET_PATH)

release: $(RELEASE_TARGET_PATH)

$(DEST_DIR) $(DEBUG_OBJDIR) $(RELEASE_OBJDIR):
	mkdir -p $@

$(DEBUG_TARGET_PATH): $(DEBUG_OBJS) | $(DEST_DIR)
	$(CC) $(COMMON_CFLAGS) $(DEBUG_CFLAGS) $^ $(LDFLAGS) -o $@

$(RELEASE_TARGET_PATH): $(RELEASE_OBJS) | $(DEST_DIR)
	$(CC) $(COMMON_CFLAGS) $(RELEASE_CFLAGS) $^ $(LDFLAGS) -o $@

$(DEBUG_OBJDIR)/%.o: $(SRCDIR)/%.c | $(DEBUG_OBJDIR)
	$(CC) $(COMMON_CFLAGS) $(DEBUG_CFLAGS) -c -o $@ $<

$(RELEASE_OBJDIR)/%.o: $(SRCDIR)/%.c | $(RELEASE_OBJDIR)
	$(CC) $(COMMON_CFLAGS) $(RELEASE_CFLAGS) -c -o $@ $<

clean:
	rm -rf $(DEBUG_OBJDIR) $(RELEASE_OBJDIR)
	rm -f $(RELEASE_TARGET_PATH)
	rm -f $(DEST_DIR)/*.o

.PHONY: all clean debug release
